networks:
  webdir:
    driver: bridge

volumes:
  db_data:
    driver: local

services:
  #mysql et adminer
  db:
    image: mysql:latest
    restart: unless-stopped
    # les variables d'environnement
    env_file:
      - ./.env
    ports:
      - "64990:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      webdir:
        aliases:
          - mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "64991:8080"
  #   networks:
  #     - webdir

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "64991:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - webdir

  #canals/php pour l'appli
  php_appli:
    image: canals/php
    working_dir: /var/www/src
    restart: unless-stopped
    ports:
      - "64992:80"
    volumes:
      - ./WebDir.core/appli/public:/var/www/html
      - ./WebDir.core/appli/src:/var/www/src
    networks:
      - webdir
    depends_on:
      - db
    
  #canals/php pour l'api
  php_api:
    image: canals/php
    working_dir: /var/www/src
    restart: unless-stopped
    ports:
      - "64993:80"
    volumes:
      - ./WebDir.core/api/public:/var/www/html
      - ./WebDir.core/api/src:/var/www/src
    networks:
      - webdir
    depends_on:
      - db

  #apache2
  apache2:
    image: ubuntu/apache2:latest
    restart: unless-stopped
    ports:
      - "64994:80"
    volumes:
      - ./WebDir.web/:/var/www/html
    networks:
      - webdir
    depends_on:
      - php_api


  
        
    
    
    

